const ActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  CHANGE_FILTER: 'CHANGE_FILTER',

};

export default ActionTypes;
