const ActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  SORT_BY_PRICE: 'SORT_BY_PRICE',
  SORT_BY_CATEGORY: 'SORT_BY_CATEGORY',
  CHANGE_FILTER: 'CHANGE_FILTER',

};

export default ActionTypes;
